version: 2.0
jobs:
    build:
        docker:
            - image: jacobniclarsen/codechan:latest
        steps:
            - run:
                name: The First Step
                command: echo 'Hello, World!'
