version: 2.0
jobs:
    build:
        docker:
            - image: jacobniclarsen/codechan:latest
        steps:
            - run:
                name: Running test
                command: python3 /usr/src/CoDeChan/test.py
